name: example
on: push
jobs:
    build_skim:
        runs-on: ubuntu-latest
        continue-on-error: true
        container: rootproject/root-conda:${{ matrix.version }}
        strategy:
            #fail-fast: false
            matrix:
                version: [6.18.04]
                allow-failure: [false]
                include:
                    - version: latest
                      allow_failure: true
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: compile skim
              run: |
                  COMPILER=$(root-config --cxx)
                  FLAGS=$(root-config --cflags --libs)
                  $COMPILER $FLAGS -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx
            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: skim${{ matrix.version }}
                  path: ./skim
    skim:
        runs-on: ubuntu-latest
        needs: build_skim
        container: rootproject/root-conda:6.18.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                  name: skim6.18.04
            - name: skim
              run: |
                  chmod +x skim
                  ./skim
