name: example
on: push
jobs:
    build_skim:
        runs-on: ubuntu-latest
        continue-on-error: true
        container: rootproject/root-conda:${{ matrix.version }}
        strategy:
            #fail-fast: false
            matrix:
                version: [6.18.04]
                allow-failure: [false]
                #include:
                #    - version: latest
                #      allow_failure: true
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: compile skim
              run: |
                  COMPILER=$(root-config --cxx)
                  FLAGS=$(root-config --cflags --libs)
                  $COMPILER $FLAGS -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx
            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: skim${{ matrix.version }}
                  path: ./skim
    skim:
        runs-on: ubuntu-latest
        needs: build_skim
        container: rootproject/root-conda:6.18.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                  name: skim6.18.04
            - name: access control
              run: |
                  printf ${{ secrets.DWSSAP }} | base64 -d | kinit ${{ secrets.EMAN_RESU }}@CERN.CH
            - name: skim
              run: |
                chmod +x skim
                ./skim root://eosuser.cern.ch//eos/user/g/gstark/AwesomeWorkshopFeb2020/GluGluToHToTauTau.root skim_ggH.root 19.6 11467.0 0.1 > skim_ggH.log
            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: skim_ggH
                  path: |
                    skim_ggH.root
                    skim_ggH.log
    histograming:
        runs-on: ubuntu-latest
        needs: skim
        container: rootproject/root-conda:6.18.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                  name: skim_ggH
            - name: produce histogram
              run: |
                  python histograms.py skim_ggH.root ggH hist_ggH.root
            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: hist_ggH
                  path: hist_ggH.root
    test_cutfow:
        runs-on: ubuntu-latest
        needs: skim
        container: rootproject/root-conda:6.18.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                  name: skim_ggH
            - name: test cutflow ggH
              run: |
                  python test_cutflow_ggH.py
    test_plot:
        runs-on: ubuntu-latest
        needs: histograming
        container: rootproject/root-conda:6.18.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                  name: hist_ggH
            - name: test cutflow ggH
              run: |
                  python test_plot_ggH.py
                  echo "theme: jekyll-theme-cayman" > deploy/_config.yml
            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: deploy
                  path: deploy
    deploy:
        runs-on: ubuntu-latest
        needs: test_plot
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                  name: deploy
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.0.0
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: deploy # The folder the action should deploy.
